### PR TITLE
Added `click` example.

### PR DESCRIPTION
**Pull request by vlcinsky**
As discussed in issue #7

### CODE REVIEW

**Comment by tailhook** [comment]
Thanks for quick response.
 
This looks good, but I see `validate` subcommand as a bit heavy-weight. I.e. for typical server process 99% of the time you just run it. I mean running the server should be the obvious thing that invoking the command does. Configuration checking on the other hand is something used more on CI systems, where adding `--check-config` is not costly. Another thing is that subcommands might actually have different configs.

So I like a `--check-config` pattern which most programs obey. Also it would be nice if click-based and argparse-based programs have same interface from the user point of view. Is it common to use a subcommand for validating configs amongs click users?

Nevertheless, I've merged the PR, as I think it's helpful addition to docs.

**Comment by vlcinsky** [comment]
@tailhook thanks for accepting the PR.

re heavy-weight - I am not sure if you measure the weight in terms of code lines or time it runs. Or visually (`--heavy-weight` looks to me lighter than `heasy-weight` : -)).

For server like applications I consider validation very important (and not being task for CI server only). If configuration is partially broken and the application does not fail immediately after starting, one can experience failure later on at unpredictable moment. Better fail at the moment administrator starts the app after reconfiguration. Solutions as `nagios`, `nginx` are following this pattern.

I learned a lot from [docopt](http://docopt.org/) about designing CLI, which is intuitive. I guess, they refer even to written POSIX standard for it. I would summarize these guidelines as:

- different actions shall use different (sub)commands
- required arguments shall be positional (thus not options) as they must be provided anyway
- options are for optional arguments

In time I have developed my own CLI pattern for my applications:

- use one main command with subcommands. This simplify use, command line name space is not spoiled with many new commands and user can simply remember just one command.
- running the main command lists all subcommands, so usage help is always at hand. Subcommands can be nested as far as needed. I do not see big difference between entering `$ app config validate` and `$ app_config_validate` and the first option is easier to do without reading documentation.
- I like the way `pserve` from pyramid works: you call `pserve config_file.ini` - thus always provide the configuration reference. This makes easy starting the application with different configuration files.
- as configuration file is required in many subcommands and any of them might have different number of positional arguments, I prefer placing the configuration file as last positional argument (unless there is a need to allow multiple positional arguments such as list of files to process).
- `click` allows usage of environment variables for providing values for options and arguments. It is easy to use an environment variable to specify the configuration file (this plays well with the previous rule to put configuration file at the end).

As you can see, the default usage style of `trafaret-config` is not in line with my expectations in regards to CLI design. On the other hand, `trafaret-config` excellently fulfils my expectations in regards to **config file validation. In this regard it is fulfilled dream**. Thanks for that.

Thinking of possible next actions:
- adding `TrafaretYamlOption` type for `click` would be handy for those, who need to use config file as an option.
- providing similar argument/option types for `argparse` could allow using the solution with argparse in any scenario (not being forced to use the `commandline` provided CLI).

If any of these actions seems promising, they should probably live in separate issues.

**Comment by tailhook** [comment]
Well, the first example on docopt site is:
```
  naval_fate ship new <name>...
  naval_fate --version
```
Where `--version` is super-similar to how `--check-config` works :)

> I like the way pserve from pyramid works: you call pserve config_file.ini - thus always provide the configuration reference. This makes easy starting the application with different configuration files.

I have one such project. This is super inconvenient. I usually prefer that local development server works without specifying config by default. Even more, if you make an alias:
```
let runapp="app --config=my/project-specific/config.yaml"
```
You still can override it on cli:
```
runapp -c config2.yaml
```
With positional arguments it's a lot harder.

Anyway, I'm not going to argue a lot about it. Just my 2 cents :)

**Comment by vlcinsky** [comment]
@tailhook You are right, `--version` and `--help` are typical exceptions. And there are other using `--start`, `--stop` etc., which I consider poorly designed.

And yes, some applications use `-c` approach to specify configuration file and if there is default one, it is perfect solution. That is why I am thinking of adding optional variant of the click class.

There are many different tastes and there is no reason to search "the correct one". Your `commandline` solution has advantage, that it can be quickly deployed and it serves the happy scenario quickly.

What I value the most on `trafaret-config` is the ability to validate and excellently report lines containing errors. And if we manage providing it for whatever CLI design style someone prefers, it will serve better.

**Pull request merged**
